### PR TITLE
Add a JUnit output formatter compatible with Jenkins

### LINKED ISSUE #107: Add Junit report
Hi,
please add a junit report option,
as a flag to the run:
should be like `bats (test files/folder) --junit`

### PR DESCRIPTION
**Pull request by josegonzalez**
Refs sstephenson/bats#161, this is a rebase of the original work onto this repository. I'll try and fix any issues that come up until its in a good place.

My reasoning for wanting this PR is to get timing support for Dokku's CircleCI runs. CircleCI only supports junit timing information, and this isn't possible via [tap-xunit](https://github.com/aghassemi/tap-xunit) as there is no timing support (see #107 for more details). Getting timing information would allow us to intelligently speed up our builds without this being a manual guess-and-check process every few months.

Hopefully closes #107.

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by josegonzalez** [comment]
One thing that the original pull request implemented was having both junit and tap output possible. I'm not able to replicate that, and would love if someone could help me take a look.

@calj I know you're a bit removed from this PR, but do you have a chance to take a look and give any good ideas here?

**Comment by makefu** [comment]
Hey Hey, any update on this PR? i'd love to see it merged to have junit export support for jenkins!

**Comment by makefu** [comment]
Btw i've tested the branch and a lot of things stopped working after that. the TAP output is broken (even if -t is used), xml output looks somewhat reasonable, but the test text output contains "malformed output" fields so i am not sure if they are parsed correctly in first place.

Cheers

**Comment by josegonzalez** [comment]
@makefu the tap output looks good to me, what exactly is broken on your end? Tests also all pass, so if you could contribute a failing test, that would be awesome :)

**Comment by makefu** [comment]
@josegonzalez With your fork of bats-core produces the same output for `bats -t tests/` and `bats tests/`. however it looks like the tests yield the same output. Maybe it has something to do if the output is the shell?

**Comment by josegonzalez** [comment]
Can you show the output before and after my changes?

**Comment by makefu** [comment]
before:
```
~/build/bats bin/bats test/fixtures/suite/multiple/a.bats 
 ✓ truth

1 test, 0 failures

~/build/bats bin/bats -t test/fixtures/suite/multiple/a.bats 
1..1
ok 1 truth

after:
```
~/build/bats-core bin/bats test/fixtures/suite/multiple/a.bats 
 ✓ truth

1 test, 0 failures

~/build/bats-core bin/bats -t test/fixtures/suite/multiple/a.bats  
 ✓ truth

1 test, 0 failures
```

**Comment by josegonzalez** [comment]
Cool I can take a look. I'm sure thats just a simple fix of me not checking for tty properly somewhere.

**Comment by makefu** [comment]
I also saw that when running with `-j -o .` then no extra output is created. i think it would be appropriate to just output the text result in bats or tap format (depending on `-t` flag).

**Comment by tterranigma** [comment]
I think that is better for the future and for extensibility to introduce a new command line option, eg `--formatter` that defines the formatter that the user wants. `--formatter pretty` could be the default. This way, users that need totally custom formatters could create their own ones without having to mess with Bats internals.

**Comment by josegonzalez** [comment]
I'm going to make `--formatter` take any binary name, so a user can specify what they want to be run. That will allow anyone to create an arbitrary executor that can mangle the output as they expect.

I'm also changing `--extended-output` to `--extra-flags`, whose value is passed to the bats test executor. This makes it so having junit output will require the following:

```shell
# The `-T` flag adds suite info when available and also adds timing. Omitting this flag will cause the `bats-format-junit` formatter to error on all test output.
# available formatters are:
# - bats-format-tap: passthru, bats format. You may also use `cat` as an alternative
# - bats-format-pretty: 
# - bats-format-junit: similar to bats-format-tap, will passthru the output, but will also parse it and write TestReport files
bin/bats -F "bats-format-junit" -e -T test/fixtures/suite/multiple
```

If you use the `bats-format-junit` formatter, you may further process the data as desired.

**Comment by makefu** [comment]
@josegonzalez fantastic progress, i'd love to see the features merged into bats

**Comment by stackfull** [comment]
Love that you're doing this. TAP is not the lingua franca it might have been - junit seems to be the common denominator for CI tools.

Unfortunately, checking out `https://github.com/josegonzalez/bats-core.git` and running the suite with formatters fails for me in interesting ways:

```
> git clone https://github.com/josegonzalez/bats-core.git
> cd bats-core
> ./bin/bats --formatter bats-format-junit test
```

Occasionally, the "extended timing syntax in suite" test fails.

The junit output (`TestReport-.xml`) always fails with entries like `<failure type="unknown"><![CDATA[
Wrong output format: ok 1 no arguments prints message and usage instructions]]></failure>`

let me know if I can help

**Comment by stackfull** [comment]
> Occasionally, the "extended timing syntax in suite" test fails.

```
not ok 71 extended timing syntax in suite
# (in test file test/suite.bats, line 88)
#   `[ "${lines[6]}" = "ok 2 more truth in 0sec" ]' failed
```

**Comment by josegonzalez** [comment]
@stackfull you're missing the flags `-e -T`, as shown in my example.

**Comment by stackfull** [comment]
> @stackfull you're missing the flags `-e -T`, as shown in my example.

Got it, thanks!

**Comment by patthiel** [comment]
Are we any closer to seeing this merged? I'd love to get me some of these nicely formatted BATS test results in CI.

**Comment by josegonzalez** [comment]
@jasonkarns is there anything you think I can do to make it easier to review/merge this PR? I _think_ everything works fine, but obviously I don't want to be pushy :)

**Comment by mmazur** [comment]
Rather unfortunate this didn't go in :(

**Comment by josegonzalez** [comment]
There was a lovely refactor of bats to add parallel support which broke this PR completely.

@sublimino given that you merged that PR, I'm assuming you're still willing to review PRs. If I rebase this PR, does it have _any_ chance of being reviewed/merged? This branch has been used since December 2018 in the Dokku repositories and has worked quite well, but if the project isn't going to land the PR, I'll just close it. No skin off my back :)

**Comment by mmazur** [comment]
I can test it as well.

**Comment by sublimino** [comment]
Hi @josegonzalez! I looked at this briefly earlier - I'm happy to review it. @bats-core/bats-core have had a little less time in 2019 than 2018, but I can start the process : ]

The feature seems sensible - @jasonkarns [raised some questions](https://github.com/bats-core/bats-core/issues/107#issuecomment-399077188) about inclusion in core but there seem to be more in favour of inclusion in the light of other solutions not working as advertised (e.g. according to that issue https://github.com/aghassemi/tap-xunit is broken / timing information is not preserved anyway).

Two initial questions:
1. Would you consider adding some tests for the Junit output?
1. Could we reduce `bats-format-junit` et al to just `junit`, `tap` etc?

I'll get into the rest by testing the rebased PR. Anything you can do to make it easier to review would be appreciated - a rebase from master (and perhaps a few squashes to tidy commit logs if you've got time).

**Comment by josegonzalez** [comment]
I'm going to close this PR. Unfortunately, a huge merge conflict was created upstream in between the time of the PR and when I last asked about rebasing. I'm not interested in spending a ton of time to do this dance again, but anyone is free to take this PR and try to re-apply to the project.

**Comment by josegonzalez** [comment]
I won't be deleting my fork, so feel free to install from that place if you absolutely need the functionality - the @dokku project is currently using it with CircleCI and it works fine.

**Comment by sublimino** [comment]
Thanks for updating @josegonzalez, and for your work on this thus far.

For the avoidance of doubt: this is currently the preferential PR for junit output. If somebody wants to get this PR to a conflict-free state it will be merged.

**Comment by martin-schulze-vireso** [comment]
@sublimino I'd be willing to take a look at this in some time. However, I'd like to avoid creating the same situation for my PR #244. How should we proceed?

**Comment by martin-schulze-vireso** [comment]
@sublimino are the other members of the bats-core organization still active? It seems the backlog of PRs and issues is piling up faster than one volunteer alone can handle.

**Comment by martin-schulze-vireso** [comment]
Okay, I tried to merge the code from this PR with mine and fix up the tests. All tests are running green but I am not sure if this worked out. Next I will try to implement it for the parallel execution.

**Comment by martin-schulze-vireso** [comment]
Just a quick heads up: I did not yet progress further, but I am still on it.

@sublimino It seems there is need for other maintainers?

**Comment by sublimino** [comment]
@martin-schulze-vireso thanks for the update. And yes, @btamayo may have further ideas for maintainers.

**Comment by sublimino** [comment]
Ooops, accidentally re-opened this PR. Closing again as work is on @martin-schulze-vireso's brach

**Pull request closed without merging**
