### PR TITLE
Add github workflow to test-build RPM

### PR DESCRIPTION
**Pull request by hecko**
Builds on Ubuntu, but this should not affect the test build outcome.

- [X] I have reviewed the [Contributor Guidelines][contributor].
- [X] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
Please add install and bats test usage, so we see the packaged version works.

**Comment by hecko** [comment]
> Please add install and bats test usage, so we see the packaged version works.

Not possible. Github does not offer rpm compatible OS. I can try to install rpm on ubuntu but this would be unreliable test.

**Comment by martin-schulze-vireso** [comment]
Are there compatible docker images?

**Comment by hecko** [comment]
https://hub.docker.com/_/almalinux

Im honestly not very sure whether this will give any additional value to the rpm build since the rpm is not signed and published anywhere. I understand your thought process, but Im unsure of the invested effort into this particular thing at this very moment. If you really want to publish the RPM and get the package into any of the major distributions the local Docker test will not suffice anyways.

**Comment by martin-schulze-vireso** [comment]
Having a succesful package build is No guarantee that the packaged software works when installed. The Idea is to have an end to end test that shows the Bats installed from RPM works as intended.

**Comment by hecko** [comment]
> Having a succesful package build is No guarantee that the packaged software works when installed. The Idea is to have an end to end test that shows the Bats installed from RPM works as intended.

Can you recommend a command to run to test the functionality of bats once installed on the system?

**Comment by hecko** [comment]
migrated to #648

**Pull request closed without merging**
