### PR TITLE
Fix parallel invocation for debian

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**
parallel's --semaphore mode does not seem to mesh well with --results.
We emulate its behavior by creating the output ourselves.

This is intended to replace #298 

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
Travis seems to be under too much load to succesfully run the strict timing tests.

**Comment by sublimino** [comment]
@martin-schulze-vireso I see the same problem — this works for me locally, but the errors on the build apparently can't be suppressed

```
parallel: Warning: ...
```

Does this mean we have to `grep -v` them out of the parallel output? :/ Is it clear to you why this wasn't a problem with the intial `parallel` patchset? Would like to get this fix out with the `readlink` changes in `1.2.1` at some point soon-ish : ]

**Comment by martin-schulze-vireso** [comment]
> Is it clear to you why this wasn't a problem with the intial parallel patchset?

The original code used `--results` to output stdout and stderr to files. This presumably separates the stderr of the task from parallels own stderr which solves this problem.

However, `--results` uses the parallel arguments (those after ::: ) to label the path. E.g.: `parallel ::: 1 2 ::: 3 4` would generate something like:
```
1/
  3/
    stdout
    stderr
  4/
    stdout
    stderr
2/
  3/
    stdout
    stderr
  4/
    stdout
    stderr
```

However, in semaphore mode we don't have those arguments so I assume that the debian version of parallel does some reads out of bounds that lead to the garbled output.

Then again this is a very specific problem: We overload the machine with too many parallel jobs and this output only makes bats fail because we check for exact output lines. I am not sure if it is a "normal" usecase to check the output of `bats --jobs` runs.

**Comment by sublimino** [comment]
@martin-schulze-vireso I've added a `grep` to the output stream to test CI in this PR. Not my finest hour (feels so cludgy) but if it works to get this feature fixed up I'm not so bothered. 

That said, happy to modify if we can find a better solution.

(I've also rebased your commit to sign it, if you are able to GPG sign I won't do this in future, but I don't mind doing it if not)

**Comment by martin-schulze-vireso** [comment]
@sublimino I'd advise to just do the warning stripping inside the test output and leave the core unchanged. If someone really has a problem with the warnings, they should tell us here. As I said above, the warnings only become errors because we test for `bats --jobs`' output line by line. Aside from internal tests I don't see a usecase for this.

**Comment by sublimino** [comment]
Ah apologies @martin-schulze-vireso I misunderstood that.

While it instinctively feels nasty to have this output in the test run, I agree the previous hack wasn't nice. I've reverted the previous and patched it in to the tests as you suggested, is this what you had in mind?

**Comment by martin-schulze-vireso** [comment]
Yes, I am still mulling over a real fix but I haven't found the time to try that yet. Just in case you want to try: Maybe we can give the semaphore mode some dummy parameters after `:::` so the path becomes more reliable.

**Comment by sublimino** [comment]
Thanks @martin-schulze-vireso, I'm on the path to releasing `1.2.1` but can loop back afterwards.

It reproduces reliably in a Debian container FWIW, I'll put this example in CI at some point https://github.com/bats-core/bats-core/issues/290#issuecomment-621292715

**Comment by martin-schulze-vireso** [comment]
Just FYI: The "real" fix I proposed above does not work. We might use a separate pipe for direct communication with the parallelized process but I don't think that this would gain much over the current solution.

**Pull request merged**
