### PR TITLE
fix: includes lib in the npm package installation

### PR DESCRIPTION
**Pull request by Ritesh-Yadav**
- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by sublimino** [comment]
Thanks @Ritesh-Yadav, are you npm installing direct from this git repo? If so can you share a command we can add to CI please?

**Comment by Ritesh-Yadav** [comment]
Hey @sublimino,

I am using following command to install:
`npm install -g git+https://github.com/bats-core/bats-core#v1.2.1`

Is there any plan to push the version to NPM?

Thanks, Ritesh

**Comment by sublimino** [comment]
Thanks for the command @Ritesh-Yadav — @jasonkarns has the NPM account that this is published under, but he doesn't have the bandwidth to publish releases these days.

@jasonkarns would you consider donating the NPM account to the bats-core organisation so we can automate the publishing of new releases to NPM?

**Review by sublimino — APPROVED** [review]
LGTM, thanks :pray:

**Comment by jasonkarns** [comment]
@sublimino yep. I can probably retro-publish the missing releases sometime this week and move the account.

I also created the bats-core organization on npm a while back (to snag it before anyone else did). So we could consider moving the package under that scope as well.  https://www.npmjs.com/org/bats-core But that's worth its own Issue/Discussion :D.

Thanks for the prompt (and PR) on this @Ritesh-Yadav !

**Pull request merged**
