### PR TITLE
Install bats binary with npm install

### PR DESCRIPTION
**Pull request by felipecrs**
So npm install --global bats && bats --version is supposed to work.

### CODE REVIEW

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by jasonkarns** [comment]
What changed with this? Per the docs, `"directories": { "bin": "bin",` is supposed to create the bin symlink already.

**Comment by jasonkarns** [comment]
Actually, this needs reverted. Not only is `bin` not supposed to be necessary, specifying _both_ is actually an error:

> If you specify a bin directory in directories.bin, all the files in that folder will be added.

> Because of the way the bin directive works, specifying both a bin path and setting directories.bin is an error. If you want to specify individual files, use bin, and for all the files in an existing bin directory, use directories.bin.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#directoriesbin

**Comment by felipecrs** [comment]
I'm really sorry about it. So it turns out that it's an issue in Volta.

https://github.com/volta-cli/volta/issues/978

**Comment by martin-schulze-vireso** [comment]
@jasonkarns I'll take that as a lesson to let my fingers off node related PRs. I read the documentation about bin and it sounded fitting. No mention about directories.bin there.

**Comment by felipecrs** [comment]
@martin-schulze-vireso @jasonkarns https://github.com/bats-core/bats-core/pull/435

**Pull request merged**
