### PR TITLE
Update Docker image with the latest `bats-file` version

### PR DESCRIPTION
**Pull request by hugocf**
See more info in https://github.com/bats-core/bats-file/issues/62#event-10175004255

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Review by brokenpip3 — APPROVED** [review]

**Comment by brokenpip3** [comment]
@hugocf can you also update the changelog?

**Comment by hugocf** [comment]
> @hugocf can you also update the changelog?

✅ Done (commit 0a712e0)

**Comment by hugocf** [comment]
@brokenpip3 can we merge this PR as it is all green?

**Comment by brokenpip3** [comment]
sorry for the late reply, looks good, however I'm not owner for the bats binary, I can merge it but I prefer to wait from someone from @bats-core/bats-core, sorry.

**Comment by martin-schulze-vireso** [comment]
Thanks for your contribution.

**Comment by marshallford** [comment]
Glad to see this PR accepted. Is there an upcoming release planned that would include this change? Currently I use `RUN /tmp/docker/install_libs.sh file 0.4.0` as a workaround. Thanks!

**Comment by martin-schulze-vireso** [comment]
I am very time constrained and the current milestone/release is constantly slipping past deadlines. My hopes are on getting some time in during holiday season but I would not bet on it.

**Pull request merged**
