### PR TITLE
Test cat formatter and update usage string

### PR DESCRIPTION
**Pull request by andregri**
- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
Thank for your suggestion. The cat formatter is intended as an internal debugging tool and as such not documented. Could you motivate why documentation and tests are warranted for this?

**Comment by andregri** [comment]
Since the cat formatter is supported by bats, it should be documented for developers or contributors. Maybe it would be better to improve the PR by adding a bit of documentation to specify that is used as an internal tool.

Even if it is an internal / debugging tool, I think that tests acts like documentation for contributors.

Eventually i added tests for completeness.

**Review by martin-schulze-vireso — CHANGES_REQUESTED** [review]
Following our previous discussion I reviewed the Code and have following suggestions:

1. Documentatiin of this formatter should only be provided in the contributor guide
2. AFAIK the only part of this formatter that is not already tested is that it prints the extended tap stream.

**Comment by andregri** [comment]
> Documentation of this formatter should only be provided in the contributor guide

Should we document cat formatter in [CONTRIBUTING.md](https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md), for instance under "Testing" section ? Or should we add `cat` option in [USAGE.md](https://github.com/bats-core/bats-core/blob/master/docs/source/usage.md)?

> AFAIK the only part of this formatter that is not already tested is that it prints the extended tap stream

 To test the extended tap stream with the cat formatter I used the same input as the test "All formatters (except cat) implement the callback interface" in [formatter.bats](https://github.com/bats-core/bats-core/blob/master/test/formatter.bats#L55).

**Comment by andregri** [comment]
I wrote few lines under the Testing section. Since it is a debugging tool, I think it may be useful to read about the cat formatter during testing.

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by martin-schulze-vireso** [comment]
Thanks for your contribution.

**Pull request merged**
