### PR TITLE
fix: use $BATS_LIBDIR instead of hardcoded lib in bats-gather-tests

### LINKED ISSUE #982: libexec/bats-core/bats-gather-tests should use $BATS_LIBDIR not /lib
**Describe the bug**
bats-gather-tests has a hard coded reference to lib and does not use $BATS_LIB when sourcing common.bash and others.

```
$ bats .
/usr/libexec/bats-core/bats-gather-tests: line 10: /usr/lib/bats-core/common.bash: No such file or directory
```

**To Reproduce**

1. Install bats-core to lib64
2. run `bats .` in a directory containing multiple bats files

**Expected behavior**
bats should run all tests

**Environment (please complete the following information):**
 - Bats version [e.g. 1.4.0 or commit hash if applicable]:  master
 - operating system (including version): [e.g. Linux (please name your distribution!), FreeBSD, MacOS]: CentOS 7.9
 - `bash --version`: [e.g. 5.1] 4.2.46
 - Install method: [e.g. git submodule, distribution package manager, npm, homebrew, ...] bash install.sh /usr lib64

Cheers,
  Peter

### PR DESCRIPTION
**Pull request by pscn**
- [ I'm an idiot] I have reviewed the [Contributor Guidelines][contributor].
- [PR without testing...  PFFF... ] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by brokenpip3** [comment]
I started the tests, can you drop a line in the changelog? check the already merged pr to check how to do it.
Thanks!

**Comment by martin-schulze-vireso** [comment]
I wonder why the tests did not catch this? IIRC there is a test with different lib path.

**Comment by martin-schulze-vireso** [comment]
I cleaned up the history and added another test that should reproduce the issue. Thanks for your contribution!

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by brokenpip3** [comment]
> I wonder why the tests did not catch this? IIRC there is a test with different lib path.

maybe in our github action we always run bats from the repo and when we use the nodejs install it will always it in the same path? we may want to add a different path matrix by testing the install.sh installation method

**Comment by martin-schulze-vireso** [comment]
I added the Tests here and fixed them in #990

**Pull request merged**
