### PR TITLE
add two distros shipping bats-core to the docs

### PR DESCRIPTION
**Pull request by henning-schild**
- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by henning-schild** [comment]
We could think about adding the name of the package the distros did choose, maybe even install instructions. But the already listed distros do not do that so i did not try.

**Comment by henning-schild** [comment]
I bet that adds some value for users, seeing that they can install the package with their distro. It also should add value to this very project, seeing and tracking who ships and appreciates the code.

**Comment by henning-schild** [comment]
in fact we also have opensuse Linux and fedora Linux, possibly more

i will try and complete the list if that gets merged or there are more questions, right now i care about Debian and Gentoo

**Comment by martin-schulze-vireso** [comment]
I think we have to be careful with the wording here. While I assume Bats to be compatible with all major Linux distributions that provide Bash, we only have a small subset of CI tested versions, which are truly "supported".

All other distributions might be listed as providing a package but should not come with the expectation of being tested, at least not from our side.

**Comment by henning-schild** [comment]
I see. In that case you decide what to do with that. Feel free to just close or throw commits on top that list distros in general and list the ones tested by bats itself.

The file is named "installation" but right it talks about tested and supported.

**Comment by martin-schulze-vireso** [comment]
I restructured the text and added some of your suggestions. Please review the new layout to see whether it is still understandable.

**Comment by henning-schild** [comment]
Looking good. You as the maintainer might find that support matrix and which one is tested how important, for a user install instructions are more relevant and the test matrix and coverage and exact versions might be something to look at when running into issues. Or maybe when having to manually install.

So all that should rather move down in the document, as additional but not primary information. Maybe all the way to the end. Hope that makes sense.

**Comment by henning-schild** [comment]
The typical scenario is ... you want to install, you read that, see your distro ... stop reading and install via that distro. Trusting it will do things right for you.

**Comment by martin-schulze-vireso** [comment]
>> Please review the [new layout](https://bats-core--659.org.readthedocs.build/en/659/installation.html) to see whether it is still understandable.
> So all that should rather move down in the document, as additional but not primary information. Maybe all the way to the end. Hope that makes sense.

I restructured a bit further and moved the support matrix into its own document. The link above points to the updated documentation.

**Comment by henning-schild** [comment]
LGTM, thanks!

**Comment by martin-schulze-vireso** [comment]
Thanks for you contribution. Sorry about the confusion, I accidentally closed instead of merging.

**Pull request merged**
