### PR TITLE
Group tests by test filename

### PR DESCRIPTION
**Pull request by nylen**
- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

This is especially useful for larger test suites.

Before:

```
 ✗ example failure
   (in test file path/to/example.bats, line 5)
     `[ "$a" = "y" ]; echo here' failed
 ✓ another test file, test 1
 ✓ another test file, test 2
 ✓ another test file, test 3
 ✓ another test file, test 4
 ✓ another test file, test 5
 ✓ another test file, test 6
 ✓ another test file, test 7
 ✓ another test file, test 8
 ✓ another test file, test 9
 ✓ another test file, test 10

11 tests, 1 failure
```

After:

```
example.bats
 ✗ example failure
   (in test file path/to/example.bats, line 5)
     `[ "$a" = "y" ]; echo here' failed
another-test-file.bats
 ✓ another test file, test 1
 ✓ another test file, test 2
 ✓ another test file, test 3
 ✓ another test file, test 4
 ✓ another test file, test 5
 ✓ another test file, test 6
 ✓ another test file, test 7
 ✓ another test file, test 8
 ✓ another test file, test 9
 ✓ another test file, test 10

11 tests, 1 failure
```

### CODE REVIEW

**Comment by nylen** [comment]
Pinging some folks who have been active here recently for review:  @sublimino @mbland @bvberkum @tterranigma

**Comment by mbland** [comment]
I'd definitely like to look into this or a similar mechanism at some point. I implemented a mechanism for http://github.com/mbland/go-script-bats that injected the relative filename (without the `.bats` extension) into the test name by computing a `SUITE` variable included in each of the test names. The ideas could perhaps be merged.

**Comment by NorseGaud** [comment]
@nylen , this is a great idea. Can you revive the PR?

**Comment by martin-schulze-vireso** [comment]
This has been superseeded by #561.

**Pull request closed without merging**
