### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by akinomyoga**
- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

I noticed inconsistent indentations in editing the files for #650. Some part of the files uses 4 spaces while double spaces are used in the other part of the same files.

I also noticed that some files (`lib/bats-core/formatter.bash`, `lib/bats-core/semaphore.bash`) are entirely indented by 4 spaces, but I have kept these files untouched though I notice that such files conflict with [Contributor Guidelines][contributor].

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
This will have to wait for the next release. Maybe we can even get everything under shfmt and instate a test that ensures no deviation.

**Comment by akinomyoga** [comment]
OK, thank you!

**Comment by jkroepke** [comment]
is `shfmt` not an option to ensure the correct formatting across the whole bats framework?

**Comment by akinomyoga** [comment]
I thought https://github.com/bats-core/bats-core/pull/651#issuecomment-1247381645 is saying `shfmt` is an option, isn't it?

**Comment by jkroepke** [comment]
You are correct. Sorry about this.

**Comment by akinomyoga** [comment]
No problem.

**Pull request merged**
