### PR TITLE
README.md: more examples of (mis)using run

### LINKED ISSUE #377: Improve the run function
The current run functions has many shortcomings and there are several issues and PRs that deal with them. This issue tries to aggregate them to get a better overview of what needs to be done:

1. globbing of `$output` into `$lines` (see #281, #289)
   1. `$lines` picks up filenames from PWD when output contains `*` (see #151, #152, #156, and #158)
   1. this also skips empty lines (see #224), which might be a feature
   1. line endings are not sanitized #249
1. bad background task lifetime through FD3 handling within run #205
1. explicitly select (only) stdout/stderr for output (see #2, #47)
1. checking the exit code on the run command itself gives better error messages (see #367)
  - [ ] write up new documentation/tutorial section for changed run behavior -> the different use cases (check exit code, check output, ...) look very different (see #366) and should be achievable with the same command

My favorite solution would be to have an interface like this:

```
run command # works as before for backwards compatibility
# exit code checking
run ! <command> # check that command failed
run =3 <command> # check that command exited with 3
# output handling
--preserve-empty-lines # default in new mode
--skip-empty-lines # default in old mode
--separate-std-out-and-err # output contains only stdout and there is $stderr
-- # mark the end of options for commands that start with -
```

This should achieve all of the above goals. If possible I'd like to reuse the existing name `run`, but we need to evaluate if that would break existing users.

### PR DESCRIPTION
**Pull request by kolyshkin**
This is a followup to #343 and closes #377.

After fixing some more code that uses `run` left and right, I am coming back
to further improve its documentation.

In particular, I try to emphasize the only use case for run (checking the output
of a command that exits with non-zero status).

I also provide a non-working example of using run with pipes.

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
Nice. I think that ties in well with #358.

**Comment by kolyshkin** [comment]
@sublimino PTAL

**Comment by sublimino** [comment]
Really nice work! These clear, simply stated documentation changes make the basics much easier for newcomers to bats, thanks @kolyshkin! You mentioned above:

> In particular, I try to emphasize the only use case for run (checking the output
of a command that exits with non-zero status).

I use `run` with https://github.com/bats-core/bats-assert#assert_output a lot, so I've added a "subshell" method to the end of the list in https://github.com/bats-core/bats-core/pull/366/commits/e0e13c327129ac7001e6278da0759d3cb2e40bb2 too :pray:

**Comment by martin-schulze-vireso** [comment]
Wow, I think this closes #1.

**Comment by martin-schulze-vireso** [comment]
With the discussion going on in #367, I would want to wait for a decision there, to avoid landing this and making it obsolete in the next step.

**Comment by sublimino** [comment]
@martin-schulze-vireso good point, I missed that one somehow! Will have a look over the weekend.

It could be worth merging this so there's a baseline to extend upon with #367, but don't mind either way.

**Comment by martin-schulze-vireso** [comment]
Just noticed that the above PR already tried to document some of this. We should

- [ ] check that #33's ideas are not lost

**Comment by martin-schulze-vireso** [comment]
> It could be worth merging this so there's a baseline to extend upon with #367, but don't mind either way.

I hope that when #367 is done, there is only one use case without `run`: Check success + get output unconditionally.

**Comment by martin-schulze-vireso** [comment]
@kolyshkin Now that #367 has landed (although the exact syntax is not settled #479), how much of this PR should we retain?

**Comment by kolyshkin** [comment]
I agree that (once we settle on "run with exit code check" syntax) this needs to be revised, as now there are more ways to achieve the same result.

Yet I think the documentation removal in #367 (e.g. https://github.com/bats-core/bats-core/pull/367/commits/ae2679709a608c3573b02b2f596616b2e063f632#diff-12cfeed9f9b1cc83679dd5e693fdf109f2080614ae71c90466cace54a187082dL54) is a mistake.

Instead, it should have been modified to show how to check exit codes.

For example, writing

```bash
run command args ...
echo "$output"
[ "$status" -eq 0 ]
```

(the first example from the removed doc) is OK but not a good style; either `command args ...` or `run 0 command args ...` is better.

**Comment by martin-schulze-vireso** [comment]
@kolyshkin You're right. I removed that part and intended to add new documentation for it but never did. We'll let this reminder sit here until we settled on the syntax.

**Comment by martin-schulze-vireso** [comment]
@kolyshkin Would you mind giving another stab at this? The `run -X`/`run !` syntax is released now, so we can move forward.

**Comment by martin-schulze-vireso** [comment]
@kolyshkin I did not hear back from you. Do you plan to work on this again?

**Comment by martin-schulze-vireso** [comment]
I reworked this according to the new `run` exit code check interface and added automatic output/stderr printing on exit code errors to `run`. This changed in the documentation in comparison to the old code:

1. "check the command succeeded": updated command to use `run`'s exit code check
2. "check the command failed": replaced by reference to `run !`
3. hide the command output: omitted, with new `run` exit code checking, the `run` command is actually shorter
4. make sure the command succeeded, and check its output: omitted, `run -0` is shorter
5. "pipe using `run`": made an extra section instead of bullet point. However, the recommendation is about to change with #663, so we might want to reword that later on

**Comment by kolyshkin** [comment]
@martin-schulze-vireso thank you, I was just checking bats-core docs and was glad to see these examples. Sorry for not following up on this myself.

**Comment by kolyshkin** [comment]
@martin-schulze-vireso I would also appreciate adding "Co-authored-by" footer next time 😉

**Comment by martin-schulze-vireso** [comment]
> @martin-schulze-vireso I would also appreciate adding "Co-authored-by" footer next time 😉 

You mean in the commit message? I am sorry that this got swept away in the many revisions this has undergone. Usually I can rely on rebase to preserve this.

**Pull request merged**
