### PR TITLE
Transfer bats#163 - Avoid undocumented usage of the head utility.

### PR DESCRIPTION
**Pull request by agent-0028**
all instances of head appear to be using -n variant now. :thumbsup:

### CODE REVIEW

**Comment by mbland** [comment]
Note that `resolve_link()` in `libexec/bats` has been rewritten to eliminate the command substitution (part of #8). You could copy that version into `install.sh` to resolve the issue.

**Comment by jasonkarns** [comment]
Closes sstephenson/bats#163

**Comment by jasonkarns** [comment]
I think it should be safe to leave the "simplified" readlink code in the install script, since there really won't be any performance concerns for the install script. (There's value in having the implementations be consistent but meh?)

**Comment by mbland** [comment]
Yeah, that's what I was thinking when I went ahead and merged it, that the install script doesn't need to be optimized per se.

**Pull request merged**
