### PR TITLE
travis: Enable build with default Linux image Bash

### PR DESCRIPTION
**Pull request by mbland**
Since I'm paranoid that we might need to resolve an issue specific to 4.3.11(1)-release (or whatever the Bash version is in the stock Travis Linux image). Also, I didn't want to hold up #116 any longer with more tiny requests.

cc: @cdevinesr

- [X] I have reviewed the [Contributor Guidelines][contributor].
- [X] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by jasonkarns** [comment]
👍  I like that this also fixes the "lie" that the macOS build was using a particular bash version.

Side question: why is the host test command `bash -c 'time bin/bats --tap test'` instead of just `time bin/bats --tap test`?

**Comment by cdevinesr** [comment]
Looks like it's been that way for a while:

```
commit bbac787615907ad06214ca2143464396d599ee5a
Author: Mike Bland <mbland@acm.org>
Date:   Sat Sep 30 11:14:48 2017 -0400

    .travis.yml: Prefix test command with `time`

    As with the update to .appveyor.yml in the previous commit, this enables
    us to get an idea of the performance impact of a change.
```

I don't personally see any reason why it couldn't be done the way @jasonkarns suggests.  It's a bit cleaner, too.

**Comment by mbland** [comment]
Heh, the `bash -c` was bugging me, too... Will sneak that in quickly here and merge once the builds pass.

**Comment by cdevinesr** [comment]
Any reason why we couldn't make the same change to the AppVeyor configuration while we're at it?

**Comment by mbland** [comment]
With AppVeyor, we have to have `bash -c` because the default shell is `CMD`, not `bash`; hence, we have to wrap the Bash commands.

**Comment by jasonkarns** [comment]
Ah, I bet that's how it snuck into travis. (copy over from appveyor?)

**Comment by mbland** [comment]
Probably. It was PR #10. Seems I was on autopilot after adding the `time` command to `.appveyor.yml`.

**Pull request merged**
