### PR TITLE
RPM build check

### PR DESCRIPTION
**Pull request by hecko**
Workflow that builds, installs and test-runs bats on AlmaLinux 8

Migrates #646 from Ubuntu runner to AlmaLinux container
Also contains #645 

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
I made the install use the local version, because it would download the latest release otherwise. The test failures are due to install.sh not being installed (which is expected) and due to something with alma not working in the timeout test. This can be reproduced without using RPM, so I think it is unrelated.

**Comment by hecko** [comment]
Is there anything else I can do here to support this merge?

**Comment by martin-schulze-vireso** [comment]
I only need to find time to finish this. I am thinking about using the new tagging feature to exclude the setup tests.

**Comment by martin-schulze-vireso** [comment]
Thanks for your contribution.

**Comment by hecko** [comment]
> Thanks for your contribution.

Thanks for maintaining bats so well.

**Pull request merged**
