### PR TITLE
Allow for output format to differ between stdout and report file

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**
This mainly deals with #342 but might incorporate #341  as well.

- [x] document --report option
- [x] update to #337's timing information, as soon as it lands

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
This should also fix #311 now. While working on the escaping of the CDATA sections I noticed the problem is more widespread. We also need to escape those parts where file names, test names, or skip messages are inserted, as they might contain characters that break the xml.

Hence, I opted for using xml escape sequences like `&lt;` instead of the CDATA only solution.

**Comment by sublimino** [comment]
I've added a commit, this looks great.

One question is flag names, currently `--formatter` and `--report`. Should the latter be `--reporter`?

I also think the `-help` text has got messy, I'll get round to cleaning that up.

**Comment by martin-schulze-vireso** [comment]
Yes, I also thought about that but reporter is a loaded word. If we are okay with a long name I would opt for `--report-format[ter]`.

**Comment by martin-schulze-vireso** [comment]
I just noticed that there is a problem when we want to use a report formatter that uses the internal extended syntax and the tap formatter which simply forwards the input. We can either forbid this combination or we have to implement a filter function on the tap formatter or we live with the invalid tap output on stdout.

**Comment by martin-schulze-vireso** [comment]
I made the TAP formatter compatible with extended syntax. For this I added `lib/bats-core/formatter.bash` to centralize the parsing logic and use callbacks for the individual formatters. I only implemented this for tap and pretty, we should move the others over to this interface as well.

In the long run this offers the opportunity to check if the formatters implement the interface correctly by at least having a definition of these callbacks, which might pave the way for a stable interface to move formatters out of bats-core.

**Comment by sublimino** [comment]
Thanks, LMK if this ready to review and merge 🙏

**Comment by martin-schulze-vireso** [comment]
@sublimino You can review now.

**Review by sublimino — APPROVED** [review]
Looks awesome, thank you @martin-schulze-vireso :100::tada:

**Pull request merged**
