### PR TITLE
docs: Add external library link to `hyperupcall/bats-all`

### PR DESCRIPTION
**Pull request by hyperupcall**
- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

Looking at the [libraries and add-ons page](https://bats-core.readthedocs.io/en/stable/writing-tests.html#libraries-and-add-ons), I was thinking other people might find the [`bats-all`](https://github.com/hyperupcall/bats-all) repository (disclaimer: I maintain it) useful.

It's useful because it reduces the burden of adding any of the official Bats libraries to any project. Instead of managing 3 (usually) repositories with `git-submodule(1)` or `git-subtree(1)` (`npm` isn't appropriate for every project), now only one repository needs to be managed. It also contains a package definition for [Basalt](https://github.com/hyperupcall/basalt), the newest Bash package manager on the block (disclaimer: I've written and maintain Basalt). It also contains a (subshell-less) `load.bash` file so it shares the idioms of the core Bats libraries for familiarity.

I've maintained it since [October of 2021](https://github.com/hyperupcall/bats-all/releases/tag/v3.0.0) and it contains the official `bats-support`, `bats-assert`, and `bats-file` repositories managed with `git-subtree(1)`. I also dogfood the repository for many other Bash projects of mine.

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
I am unsure what to do with this. Surely there are people who might benefit from this. On the other hand, looking at the section you want to insert this into, I would rather remove that whole section from the documentation.

In general, we there is an ecosystem of plugins and extension around Bats that we don't control and that your project is part of. Recommending these by linking to them in our docs gives them some semi official status. I would not want to be responsible for any issues with those linked libraries, so we would need a disclaimer. Maybe we should use community edited wiki page like https://github.com/bats-core/bats-core/wiki/Projects-Using-Bats to represent the ecosystem.

**Comment by hyperupcall** [comment]
I see, adding this repository to the official documentation may appear to give it semi-official status even though my project is not officially related. A community-edited wiki page may be a better place to put this information, but I'm not sure how discoverable it would be (I've been using Bats for years and I did not know it had a wiki). Nevertheless, it would probably be better placed there and a page that contains help libraries does sound like a good idea

**Comment by hyperupcall** [comment]
I made a new page: https://github.com/bats-core/bats-core/wiki/Libraries-For-Bats

**Comment by martin-schulze-vireso** [comment]
> A community-edited wiki page may be a better place to put this information, but I'm not sure how discoverable it would be (I've been using Bats for years and I did not know it had a wiki).

That can be helped. I have no problem with linking to that wiki page from our docs.

**Pull request closed without merging**
