### PR TITLE
Remove unused BATS_TEST_FILTER

### PR DESCRIPTION
**Pull request by debarshiray**
Fallout from 67822e2c4501c0d364b86a34cd469b941df0e64f and
9d5ecdbe319bd0e39ef2637806832bb07768fb23

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
I am unsure as well and have half a mind of folding this into your other PR.

**Comment by debarshiray** [comment]
> I am unsure as well and have half a mind of folding this into your other PR.

Whatever you decide is fine with me.  :)

**Comment by debarshiray** [comment]
Looks like I need to rebase this against `master`.  I will take a look at it soon.

**Comment by debarshiray** [comment]
> Looks like I need to rebase this against `master`. I will take a look at it soon.

Done

**Comment by martin-schulze-vireso** [comment]
I rebased again and added a changelog entry. Thanks for you contribution!

**Review by martin-schulze-vireso — APPROVED** [review]

**Pull request merged**
