### PR TITLE
Rebased #191 to current master

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**
this obsoletes #191 

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by lucastheisen** [comment]
Looks good to me!

**Comment by martin-schulze-vireso** [comment]
@sublimino Since I resubmitted this, I had to use admin privileges to merge despite having a review (since I can't review my own PR). Let me know if you have any objections. We already reviewed the previous PR (#191), so I assumed you are fine with it.

**Comment by cornfeedhobo** [comment]
@martin-schulze-vireso any chance you'll release a new tag soon?

**Comment by martin-schulze-vireso** [comment]
@cornfeedhobo I assume you post this here, because you are waiting for this feature?

I was planning on piling up some more changes before cutting a new release but I guess I have been dragging my feet too long on those issues. I'll talk to the other maintainers if we should make a new release already.

**Comment by cornfeedhobo** [comment]
@martin-schulze-vireso you guessed it :laughing:, but I'm not in any rush, so please don't feel pressured. I just wanted to ask because I didn't sense a defined schedule when looking at the current tags. Thanks for the prompt reply!

**Pull request merged**
