### PR TITLE
Serhat

### PR DESCRIPTION
**Pull request by karakartal1881**
- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by karakartal1881** [comment]
https://github.com/bats-core/bats-core/pull/389#issue-542110828https://github.com/bats-core/bats-core/pull/389#issue-542110828

**Comment by karakartal1881** [comment]
harika

**Comment by martin-schulze-vireso** [comment]
I have blocked this user now as a repeat offender.

**Comment by karakartal1881** [comment]
Katılımcı Yönergelerini inceledim .
Davranış Kurallarını inceledim ve ona uymayı kabul ediyorum

**Pull request closed without merging**
