### PR TITLE
Add a script for uninstalling

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
Please add tests that ensure all bats files but no other files are removed.

**Comment by masatake** [comment]
Do I have to do something for merging this pull request?

**Comment by martin-schulze-vireso** [comment]
I rebased your commits to sign them and squashed everything into one commit.

**Review by martin-schulze-vireso — APPROVED** [review]

**Comment by masatake** [comment]
Thank you.

**Pull request merged**
